import React, { createContext, useContext, useState, useCallback } from 'react';

const LANGUAGES = {  uz: { label: "O'zbek", flag: 'UZB' },
  ru: { label: 'Русский', flag: 'RUS' },
  en: { label: 'English', flag: 'ENG' },
};

const TRANSLATIONS = {
  uz: {
    // Header
    'app.name': 'GazQueue',
    'header.login': 'Kirish',
    'header.profile': 'Profil',
    'header.back': 'Orqaga',
    'header.theme.light': "Qorong'u rejim",
    'header.theme.dark': "Yorug' rejim",

    // Hero
    'hero.badge': 'Toshkent · Real-time navbat tizimi',
    'hero.title1': 'Gaz navbatini',
    'hero.title2': 'online boshqaring',
    'hero.desc': "Yaqin AZS ni toping, real vaqtda navbatni kuzating va vaqtingizni tejang. 18 ta metan stansiyasi ulangan.",
    'hero.btn.queue': '🚗 Navbatga yozilish',
    'hero.btn.find': '📍 Stansiya topish',
    'hero.trust.realtime': 'Real-time yangilanish',
    'hero.trust.secure': 'Xavfsiz tizim',
    'hero.trust.mobile': 'Mobil qurilmalar uchun',

    // Stats
    'stats.total': 'Jami stansiyalar',
    'stats.open': 'Ochiq stansiyalar',
    'stats.online': 'Onlayn foydalanuvchilar',
    'stats.active': 'Aktiv navbatlar',
    'stats.avgwait': "O'rtacha kutish",
    'stats.today': 'Bugun xizmat',

    // Map
    'map.title': 'Metan AZS xaritasi',
    'map.desc': "Toshkent bo'ylab 18 ta stansiya · Xaritadan stansiya tanlang",
    'map.filter': 'Holat:',
    'map.free': "Navbat yo'q",
    'map.medium': "O'rtacha",
    'map.busy': 'Band',
    'map.nearest': 'Eng yaqin',
    'map.route': "Yo'l",
    'map.station_count': 'ta stansiya',
    'map.nearest_label': 'Eng yaqin:',
    'map.route_label': "Yo'l:",

    // Station cards
    'stations.title': 'Yaqin AZS lar',
    'stations.queue': 'ta',
    'stations.wait': 'min',
    'stations.join': 'Navbatga yozilish →',
    'stations.open': 'Ochiq',
    'stations.closed': '🔒 Yopiq',
    'stations.cars': 'ta',
    'stations.rating': '★',

    // Queue
    'queue.title': 'Online navbat',
    'queue.selected': 'Tanlangan stansiya',
    'queue.select_prompt': "⬆️ Xaritadan stansiya tanlang",
    'queue.gas_yes': '✅ Gaz mavjud',
    'queue.gas_no': "❌ Gaz yo'q",
    'queue.status': 'Navbat holati',
    'queue.empty': "Navbat bo'sh",
    'queue.you': 'Siz',
    'queue.first': 'Navbatda',
    'queue.name': 'Ism',
    'queue.name_placeholder': "To'liq ismingiz",
    'queue.car': 'Mashina raqami',
    'queue.car_placeholder': 'Masalan: 01 A 123 BC',
    'queue.gas_amount': 'Gaz miqdori',
    'queue.join_btn': '🚗 Navbatga yozilish',
    'queue.leave_btn': 'Navbatdan chiqish',
    'queue.loading': 'Yuklanmoqda...',
    'queue.position': "o'rindasiz",
    'queue.ahead': 'kishi oldingizda',
    'queue.at_station': 'stansiyasida navbatdasiz',

    // Register
    'reg.title': 'Hisobingizni yarating',
    'reg.subtitle': 'GazQueue orqali navbatga onlayn yoziling',
    'reg.tab.register': "Ro'yxatdan o'tish",
    'reg.tab.login': 'Kirish',
    'reg.fullname': "To'liq ism",
    'reg.phone': 'Telefon raqam',
    'reg.carnumber': 'Mashina raqami',
    'reg.car_example': 'Masalan: 01 A 123 BC yoki 30 BBA 456',
    'reg.password': 'Parol',
    'reg.password_hint': 'Kamida 8 ta belgi',
    'reg.confirm': 'Parolni tasdiqlang',
    'reg.confirm_hint': 'Parolni qayta kiriting',
    'reg.terms1': 'Foydalanish shartlari',
    'reg.terms2': 'Maxfiylik siyosati',
    'reg.terms_agree': 'bilan roziman',
    'reg.submit': "Ro'yxatdan o'tish",
    'reg.login_title': 'Hisobga kirish',
    'reg.login_phone': 'Telefon raqam',
    'reg.login_password': 'Parol',
    'reg.login_forgot': 'Parolni unutdingizmi?',
    'reg.login_submit': 'Kirish',
    'reg.login_checking': 'Tekshirilmoqda...',
    'reg.info_title': "Nima uchun ro'yxatdan o'tish kerak?",
    'reg.info_desc': 'Navbatga onlayn yozilish, holatingizni kuzatish va bildirishnomalar olish uchun hisob kerak.',
    'reg.success_title': 'Muvaffaqiyat! 🎉',
    'reg.success_desc': "Siz muvaffaqiyatli ro'yxatdan o'tdingiz. Endi navbatga yozilishingiz mumkin.",
    'reg.success_btn': "Bosh sahifaga o'tish",
    'reg.login_error': "Telefon yoki parol noto'g'ri",
    'reg.login_network_error': 'Server bilan bog\'lanishda xatolik',
    'reg.error.name': "Iltimos, to'liq ismingizni kiriting.",
    'reg.error.phone': "Telefon raqamni to'liq kiriting.",
    'reg.error.car': 'Mashina raqamini kiriting.',
    'reg.error.password': "Parol kamida 8 ta belgidan iborat bo'lishi kerak.",
    'reg.error.confirm': 'Parollar mos kelmaydi.',
    'reg.error.terms': "Foydalanish shartlari bilan rozilashishingiz kerak.",
    'reg.password_strength.very_weak': 'Juda zaif',
    'reg.password_strength.weak': 'Zaif',
    'reg.password_strength.medium': "O'rtacha",
    'reg.password_strength.strong': 'Kuchli 💪',

    // Toast messages
    'toast.station_selected': 'tanlandi',
    'toast.select_station': "Avval xaritadan stansiya tanlang",
    'toast.enter_name': 'Ismingizni kiriting',
    'toast.enter_car': 'Mashina raqamini kiriting',
    'toast.select_gas': 'Gaz miqdorini tanlang',
    'toast.join_success': "Navbatga muvaffaqiyatli yozildingiz! 🎉",
    'toast.leave_success': 'Navbatdan chiqdingiz',
    'toast.error': 'Xatolik yuz berdi',

    // Gas options
    'gas.half': 'Yarim balon',
    'gas.half_sub': "25 000 so'm",
    'gas.full': "To'liq balon",
    'gas.full_sub': "50 000 so'm",
    'gas.custom': 'Miqdor',
    'gas.custom_sub': "O'zim aytaman",
    'gas.urgent': 'Shoshilinch',
    'gas.urgent_sub': 'Ozgina kerak',

    // Footer
    'footer.queue': 'Navbat',
    'footer.azs': 'AЗС',
    'footer.notifications': 'Bildirishnomalar',
    'footer.admin': 'Admin',
    'footer.station': 'Stansiya',
    'footer.profile': 'Profil',
    'footer.login': 'Kirish',

    // Mobile nav
    'mob.home': 'Asosiy',
    'mob.azs': 'AZS',
    'mob.queue': 'Navbat',
    'mob.notif': 'Bildirishnoma',
    'mob.profile': 'Profil',

    // Admin sidebar
    'admin.panel': 'Admin Panel',
    'admin.nav.main': 'Asosiy',
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.stations': 'Stansiyalar',
    'admin.nav.queues': 'Navbatlar',
    'admin.nav.users': 'Foydalanuvchilar',
    'admin.nav.analytics': 'Analitika',
    'admin.nav.settings': 'Sozlamalar',
    'admin.nav.account': 'Hisob',
    'admin.logout': 'Chiqish',

    // Admin Login
    'admin.login.title': 'Kirish',
    'admin.login.subtitle': 'Admin yoki AZS xodimi uchun',
    'admin.login.phone': 'Telefon raqam',
    'admin.login.password': 'Parol',
    'admin.login.checking': 'Tekshirilmoqda...',
    'admin.login.submit': 'Kirish',
    'admin.login.back': '← Bosh sahifaga qaytish',
    'admin.login.error': "Telefon yoki parol noto'g'ri",
    'admin.login.empty_error': 'Telefon va parolni kiriting',
    'admin.login.generic_error': 'Xatolik yuz berdi',

    // Station Login
    'station.login.title': 'AZS Admin kirish',
    'station.login.subtitle': 'Zaправка xodimi uchun',

    // Station Admin
    'station.panel': 'Admin panel',
    'station.gas.title': "⛽ Gaz holati (mijozlarga ko'rinadi)",
    'station.gas.yes': '✅ Gaz bor',
    'station.gas.no': "❌ Gaz yo'q",
    'station.gas.message_placeholder': "Qo'shimcha xabar (ixtiyoriy)...",
    'station.gas.eta_placeholder': "Kelish vaqti (faqat yo'q bo'lsa)...",
    'station.gas.save': 'Saqlash',
    'station.gas.saved': '✓ Saqlandi',
    'station.sections': 'Seksiyalar',
    'station.sections.count': 'Seksiya soni:',
    'station.sections.empty': "Bo'sh",
    'station.sections.done': '✓ Tayyor',
    'station.queue': "Navbat ro'yxati",
    'station.queue.clear': 'Tozalash',
    'station.queue.empty': "Navbat bo'sh",
    'station.stats.queue': 'Navbatda',
    'station.stats.served': "Xizmat ko'rsatildi",
    'station.stats.busy': 'Band seksiyalar',
    'station.stats.today': 'Bugun zaправka',
    'station.history': 'Zaправka tarixi',
    'station.history.browser': 'Brauzerda saqlanadi',
    'station.history.empty': "Hali zaправkalar yo'q",
    'station.history.clear': 'Tozalash',
    'station.history.confirm_clear': "Barcha tarixni o'chirishni tasdiqlaysizmi?",
    'station.confirm_clear_queue': 'Navbatni tozalashni tasdiqlaysizmi?',
    'station.reviews': 'Mijozlar baholari',
    'station.reviews.empty': "Hali baholashlar yo'q",
    'station.reviews.avg': "o'rtacha",
    'station.reviews.ta': 'ta',
    'station.logout': 'Chiqish',

    // History
    'history.title': 'Zaправka tarixi',
    'history.stats.today': 'Bugun',
    'history.stats.total': 'Jami',
    'history.stats.top': "Ko'p so'ralgan",
    'history.filter': 'Filter:',
    'history.filter.all': 'Hammasi',
    'history.filter.today': 'Bugun',
    'history.filter.week': 'Bu hafta',
    'history.search': 'Ism yoki mashina raqami...',
    'history.empty.title': "Tarix bo'sh",
    'history.empty.desc': 'Zaправkalar tugagandan keyin bu yerda ko\'rinadi',
    'history.table.number': '#',
    'history.table.name': 'Ism',
    'history.table.car': 'Mashina',
    'history.table.gas': 'Gaz miqdori',
    'history.table.section': 'Seksiya',
    'history.table.time': 'Sana · Vaqt',
    'history.today': 'Bugun',
    'history.clear': 'Tozalash',
    'history.confirm_clear': "Barcha tarixni o'chirishni tasdiqlaysizmi?",

    // Notifications
    'notif.title': 'Bildirishnomalar',
    'notif.read_all': "Barchasini o'qildi",
    'notif.empty.title': "Bildirishnomalar yo'q",
    'notif.empty.desc': 'Navbatga yozilganda bu yerda ko\'rinadi',
    'notif.login.title': 'Avval navbatga yoziling',
    'notif.login.btn': 'Bosh sahifaga',
    'notif.just_now': 'Hozirgina',
    'notif.min_ago': 'daqiqa oldin',
    'notif.hour_ago': 'soat oldin',

    // Profile
    'profile.overview': 'Profil',
    'profile.queue': 'Navbatim',
    'profile.history': 'Tarix',
    'profile.favorites': 'Sevimlilar',
    'profile.settings': 'Sozlamalar',
    'profile.edit': '✏️ Tahrirlash',
    'profile.logout': '🚪 Chiqish',
    'profile.tab.overview': "Umumiy ko'rinish",
    'profile.stats.queue': 'Navbat',
    'profile.stats.visits': 'Tashriflar',
    'profile.stats.favorites': 'Sevimlilar',
    'profile.stats.none': "Yo'q",
    'profile.active_queue': '⛽ Faol navbat',
    'profile.view': "Ko'rish",
    'profile.recent_notifs': '🔔 Oxirgi bildirishnomalar',
    'profile.see_all': "Hammasini ko'rish →",
    'profile.fav_stations': '⭐ Sevimli stansiyalar',
    'profile.my_queue': '🚗 Mening navbatim',
    'profile.queue_active': 'Siz navbatdasiz',
    'profile.queue_none': "Faol navbat yo'q",
    'profile.queue_none_desc': "Hozirda hech qanday stansiyada navbatda turmaysiz",
    'profile.queue_join': '🚗 Navbatga yozilish',
    'profile.queue_leave': 'Navbatdan chiqish',
    'profile.queue_position': "O'rin",
    'profile.queue_total': 'Navbatda',
    'profile.queue_minutes': 'Daqiqa',
    'profile.queue_est': '~',
    'profile.history_title': '📋 Tashriflar tarixi',
    'profile.history_empty': "Tarix bo'sh",
    'profile.history_empty_desc': 'Zaправka qilganingizdan keyin bu yerda ko\'rinadi',
    'profile.fav_title': '⭐ Sevimli stansiyalar',
    'profile.fav_empty': 'Sevimli stansiyalar yo\'q',
    'profile.fav_empty_desc': "Xaritadan stansiyani tanlab sevimlilarga qo'shing",
    'profile.fav_open_map': '📍 Xaritani ochish',
    'profile.settings_profile': '👤 Profil sozlamalari',
    'profile.settings_name': 'Ism',
    'profile.settings_car': 'Mashina raqami',
    'profile.settings_phone_note': "📞 Telefon raqamni o'zgartirish uchun admin bilan bog'laning",
    'profile.settings_save': '💾 Profilni yangilash',
    'profile.settings_password': '🔐 Parolni o\'zgartirish',
    'profile.settings_old_pass': 'Eski parol',
    'profile.settings_new_pass': 'Yangi parol',
    'profile.settings_confirm_pass': 'Yangi parolni tasdiqlang',
    'profile.settings_pass_placeholder': 'Kamida 6 belgi',
    'profile.settings_confirm_placeholder': 'Qayta kiriting',
    'profile.settings_pass_update': '🔒 Parolni yangilash',
    'profile.settings_app_version': 'Ilova versiyasi',
    'profile.settings_language': 'Til',
    'profile.settings_member_since': "A'zo bo'lgan",
    'profile.fav_station_open': '✅ Ochiq',
    'profile.fav_station_closed': '🔒 Yopiq',
    'profile.open': 'Ochiq',
    'profile.closed': 'Yopiq',

    // Review Modal
    'review.title': 'Xizmatimizni baholang',
    'review.desc': 'Xizmat yakunlandi',
    'review.thanks_title': 'Rahmat!',
    'review.thanks_desc': 'Sizning fikringiz bizga juda muhim',
    'review.comment_placeholder': 'Izoh qoldiring (ixtiyoriy)...',
    'review.submit': 'Yuborish',
    // Arrival time
    'arrival.title': 'Vaqtni tanlang',
    'arrival.subtitle': 'qachon kelishingizni belgilang',
    'arrival.now': 'Hozir',
    'arrival.now_desc': 'Kutishga tayyor',
    'arrival.15min': '15 min',
    'arrival.15min_desc': '15 daqiqadan keyin',
    'arrival.30min': '30 min',
    'arrival.30min_desc': '30 daqiqadan keyin',
    'arrival.1hour': '1 soat',
    'arrival.1hour_desc': '1 soatdan keyin',
    'arrival.custom': 'Boshqa',
    'arrival.custom_desc': 'Vaqtni belgilang',

    'review.skip': "O'tkazib yuborish",
  },

  ru: {
    'app.name': 'GazQueue',
    'header.login': 'Войти',
    'header.profile': 'Профиль',
    'header.back': 'Назад',
    'header.theme.light': 'Тёмная тема',
    'header.theme.dark': 'Светлая тема',

    'hero.badge': 'Ташкент · Система очередей в реальном времени',
    'hero.title1': 'Управляйте очередью',
    'hero.title2': 'на газ онлайн',
    'hero.desc': 'Найдите ближайшую АЗС, следите за очередью в реальном времени и экономьте время. Подключено 18 метановых станций.',
    'hero.btn.queue': '🚗 Встать в очередь',
    'hero.btn.find': '📍 Найти станцию',
    'hero.trust.realtime': 'Обновление в реальном времени',
    'hero.trust.secure': 'Безопасная система',
    'hero.trust.mobile': 'Для мобильных устройств',

    'stats.total': 'Всего станций',
    'stats.open': 'Открыто станций',
    'stats.online': 'Пользователей онлайн',
    'stats.active': 'Активных очередей',
    'stats.avgwait': 'Среднее ожидание',
    'stats.today': 'Обслужено сегодня',

    'map.title': 'Карта метановых АЗС',
    'map.desc': '18 станций по всему Ташкенту · Выберите станцию на карте',
    'map.filter': 'Статус:',
    'map.free': 'Нет очереди',
    'map.medium': 'Средняя',
    'map.busy': 'Занято',
    'map.nearest': 'Ближайшая',
    'map.route': 'Маршрут',
    'map.station_count': 'станций',
    'map.nearest_label': 'Ближайшая:',
    'map.route_label': 'Маршрут:',

    'stations.title': 'Ближайшие АЗС',
    'stations.queue': 'шт',
    'stations.wait': 'мин',
    'stations.join': 'Встать в очередь →',
    'stations.open': 'Открыто',
    'stations.closed': '🔒 Закрыто',
    'stations.cars': 'шт',
    'stations.rating': '★',

    'queue.title': 'Онлайн очередь',
    'queue.selected': 'Выбранная станция',
    'queue.select_prompt': '⬆️ Выберите станцию на карте',
    'queue.gas_yes': '✅ Газ есть',
    'queue.gas_no': '❌ Газа нет',
    'queue.status': 'Состояние очереди',
    'queue.empty': 'Очередь пуста',
    'queue.you': 'Вы',
    'queue.first': 'В очереди',
    'queue.name': 'Имя',
    'queue.name_placeholder': 'Полное имя',
    'queue.car': 'Номер авто',
    'queue.car_placeholder': 'Например: 01 A 123 BC',
    'queue.gas_amount': 'Количество газа',
    'queue.join_btn': '🚗 Встать в очередь',
    'queue.leave_btn': 'Выйти из очереди',
    'queue.loading': 'Загрузка...',
    'queue.position': 'место',
    'queue.ahead': 'человек перед вами',
    'queue.at_station': '- вы в очереди',

    'reg.title': 'Создайте аккаунт',
    'reg.subtitle': 'Встаньте в очередь онлайн через GazQueue',
    'reg.tab.register': 'Регистрация',
    'reg.tab.login': 'Вход',
    'reg.fullname': 'Полное имя',
    'reg.phone': 'Номер телефона',
    'reg.carnumber': 'Номер машины',
    'reg.car_example': 'Например: 01 A 123 BC или 30 BBA 456',
    'reg.password': 'Пароль',
    'reg.password_hint': 'Минимум 8 символов',
    'reg.confirm': 'Подтвердите пароль',
    'reg.confirm_hint': 'Введите пароль ещё раз',
    'reg.terms1': 'Условия использования',
    'reg.terms2': 'Политика конфиденциальности',
    'reg.terms_agree': 'Я согласен с',
    'reg.submit': 'Зарегистрироваться',
    'reg.login_title': 'Войти в аккаунт',
    'reg.login_phone': 'Номер телефона',
    'reg.login_password': 'Пароль',
    'reg.login_forgot': 'Забыли пароль?',
    'reg.login_submit': 'Войти',
    'reg.login_checking': 'Проверка...',
    'reg.info_title': 'Зачем регистрироваться?',
    'reg.info_desc': 'Аккаунт нужен чтобы вставать в очередь онлайн, отслеживать статус и получать уведомления.',
    'reg.success_title': 'Успешно! 🎉',
    'reg.success_desc': 'Вы успешно зарегистрировались. Теперь вы можете встать в очередь.',
    'reg.success_btn': 'На главную',
    'reg.login_error': 'Неверный телефон или пароль',
    'reg.login_network_error': 'Ошибка соединения с сервером',
    'reg.error.name': 'Пожалуйста, введите полное имя.',
    'reg.error.phone': 'Введите номер телефона полностью.',
    'reg.error.car': 'Введите номер машины.',
    'reg.error.password': 'Пароль должен содержать минимум 8 символов.',
    'reg.error.confirm': 'Пароли не совпадают.',
    'reg.error.terms': 'Вы должны согласиться с условиями использования.',
    'reg.password_strength.very_weak': 'Очень слабый',
    'reg.password_strength.weak': 'Слабый',
    'reg.password_strength.medium': 'Средний',
    'reg.password_strength.strong': 'Сильный 💪',

    'toast.station_selected': 'выбрана',
    'toast.select_station': 'Сначала выберите станцию на карте',
    'toast.enter_name': 'Введите ваше имя',
    'toast.enter_car': 'Введите номер машины',
    'toast.select_gas': 'Выберите количество газа',
    'toast.join_success': 'Вы успешно встали в очередь! 🎉',
    'toast.leave_success': 'Вы вышли из очереди',
    'toast.error': 'Произошла ошибка',

    'gas.half': 'Полбака (~20L)',
    'gas.half_sub': '25 000 сум',
    'gas.full': 'Полный бак (~40L)',
    'gas.full_sub': '50 000 сум',
    'gas.custom': 'Своё количество',
    'gas.custom_sub': 'Скажу сам',
    'gas.urgent': 'Срочно',
    'gas.urgent_sub': 'Немного нужно',

    'footer.queue': 'Очередь',
    'footer.azs': 'АЗС',
    'footer.notifications': 'Уведомления',
    'footer.admin': 'Админ',
    'footer.station': 'Станция',
    'footer.profile': 'Профиль',
    'footer.login': 'Вход',

    'mob.home': 'Главная',
    'mob.azs': 'АЗС',
    'mob.queue': 'Очередь',
    'mob.notif': 'Уведомления',
    'mob.profile': 'Профиль',

    'admin.panel': 'Админ панель',
    'admin.nav.main': 'Главное',
    'admin.nav.dashboard': 'Дашборд',
    'admin.nav.stations': 'Станции',
    'admin.nav.queues': 'Очереди',
    'admin.nav.users': 'Пользователи',
    'admin.nav.analytics': 'Аналитика',
    'admin.nav.settings': 'Настройки',
    'admin.nav.account': 'Аккаунт',
    'admin.logout': 'Выйти',
    'admin.login.title': 'Вход',
    'admin.login.subtitle': 'Для админа или сотрудника АЗС',
    'admin.login.phone': 'Номер телефона',
    'admin.login.password': 'Пароль',
    'admin.login.checking': 'Проверка...',
    'admin.login.submit': 'Войти',
    'admin.login.back': '← Вернуться на главную',
    'admin.login.error': 'Неверный телефон или пароль',
    'admin.login.empty_error': 'Введите телефон и пароль',
    'admin.login.generic_error': 'Произошла ошибка',

    'station.login.title': 'Вход для сотрудника АЗС',
    'station.login.subtitle': 'Для сотрудника станции',

    'station.panel': 'Панель администратора',
    'station.gas.title': '⛽ Статус газа (виден клиентам)',
    'station.gas.yes': '✅ Газ есть',
    'station.gas.no': '❌ Газа нет',
    'station.gas.message_placeholder': 'Дополнительное сообщение (необязательно)...',
    'station.gas.eta_placeholder': 'Время прибытия (если газа нет)...',
    'station.gas.save': 'Сохранить',
    'station.gas.saved': '✓ Сохранено',
    'station.sections': 'Секции',
    'station.sections.count': 'Количество секций:',
    'station.sections.empty': 'Свободно',
    'station.sections.done': '✓ Готово',
    'station.queue': 'Список очереди',
    'station.queue.clear': 'Очистить',
    'station.queue.empty': 'Очередь пуста',
    'station.stats.queue': 'В очереди',
    'station.stats.served': 'Обслужено',
    'station.stats.busy': 'Занято секций',
    'station.stats.today': 'Обслужено сегодня',
    'station.history': 'История заправок',
    'station.history.browser': 'Хранится в браузере',
    'station.history.empty': 'Заправок пока нет',
    'station.history.clear': 'Очистить',
    'station.history.confirm_clear': 'Вы уверены, что хотите очистить всю историю?',
    'station.confirm_clear_queue': 'Вы уверены, что хотите очистить очередь?',
    'station.reviews': 'Отзывы клиентов',
    'station.reviews.empty': 'Отзывов пока нет',
    'station.reviews.avg': 'среднее',
    'station.reviews.ta': 'шт',
    'station.logout': 'Выйти',

    'history.title': 'История заправок',
    'history.stats.today': 'Сегодня',
    'history.stats.total': 'Всего',
    'history.stats.top': 'Чаще всего',
    'history.filter': 'Фильтр:',
    'history.filter.all': 'Все',
    'history.filter.today': 'Сегодня',
    'history.filter.week': 'Эта неделя',
    'history.search': 'Имя или номер авто...',
    'history.empty.title': 'История пуста',
    'history.empty.desc': 'Появится здесь после заправки',
    'history.table.number': '#',
    'history.table.name': 'Имя',
    'history.table.car': 'Авто',
    'history.table.gas': 'Кол-во газа',
    'history.table.section': 'Секция',
    'history.table.time': 'Дата · Время',
    'history.today': 'Сегодня',
    'history.clear': 'Очистить',
    'history.confirm_clear': 'Вы уверены, что хотите очистить всю историю?',

    'notif.title': 'Уведомления',
    'notif.read_all': 'Прочитать всё',
    'notif.empty.title': 'Нет уведомлений',
    'notif.empty.desc': 'Появятся здесь после вступления в очередь',
    'notif.login.title': 'Сначала встаньте в очередь',
    'notif.login.btn': 'На главную',
    'notif.just_now': 'Только что',
    'notif.min_ago': 'мин назад',
    'notif.hour_ago': 'час назад',

    'profile.overview': 'Профиль',
    'profile.queue': 'Моя очередь',
    'profile.history': 'История',
    'profile.favorites': 'Избранное',
    'profile.settings': 'Настройки',
    'profile.edit': '✏️ Редактировать',
    'profile.logout': '🚪 Выйти',
    'profile.tab.overview': 'Обзор',
    'profile.stats.queue': 'Очередь',
    'profile.stats.visits': 'Визиты',
    'profile.stats.favorites': 'Избранное',
    'profile.stats.none': 'Нет',
    'profile.active_queue': '⛽ Активная очередь',
    'profile.view': 'Смотреть',
    'profile.recent_notifs': '🔔 Последние уведомления',
    'profile.see_all': 'Все →',
    'profile.fav_stations': '⭐ Избранные станции',
    'profile.my_queue': '🚗 Моя очередь',
    'profile.queue_active': 'Вы в очереди',
    'profile.queue_none': 'Нет активной очереди',
    'profile.queue_none_desc': 'Вы сейчас не стоите в очереди ни на одной станции',
    'profile.queue_join': '🚗 Встать в очередь',
    'profile.queue_leave': 'Выйти из очереди',
    'profile.queue_position': 'Место',
    'profile.queue_total': 'В очереди',
    'profile.queue_minutes': 'Минут',
    'profile.queue_est': '~',
    'profile.history_title': '📋 История посещений',
    'profile.history_empty': 'История пуста',
    'profile.history_empty_desc': 'Появится здесь после заправки',
    'profile.fav_title': '⭐ Избранные станции',
    'profile.fav_empty': 'Нет избранных станций',
    'profile.fav_empty_desc': 'Выберите станцию на карте, чтобы добавить в избранное',
    'profile.fav_open_map': '📍 Открыть карту',
    'profile.settings_profile': '👤 Настройки профиля',
    'profile.settings_name': 'Имя',
    'profile.settings_car': 'Номер авто',
    'profile.settings_phone_note': '📞 Свяжитесь с админом для смены номера',
    'profile.settings_save': '💾 Обновить профиль',
    'profile.settings_password': '🔐 Смена пароля',
    'profile.settings_old_pass': 'Старый пароль',
    'profile.settings_new_pass': 'Новый пароль',
    'profile.settings_confirm_pass': 'Подтвердите пароль',
    'profile.settings_pass_placeholder': 'Минимум 6 символов',
    'profile.settings_confirm_placeholder': 'Введите ещё раз',
    'profile.settings_pass_update': '🔒 Обновить пароль',
    'profile.settings_app_version': 'Версия приложения',
    'profile.settings_language': 'Язык',
    'profile.settings_member_since': 'Участник с',
    'profile.fav_station_open': '✅ Открыто',
    'profile.fav_station_closed': '🔒 Закрыто',
    'profile.open': 'Открыто',
    'profile.closed': 'Закрыто',

    'review.title': 'Оцените наш сервис',
    'review.desc': 'Услуга выполнена',
    'review.thanks_title': 'Спасибо!',
    'review.thanks_desc': 'Ваше мнение очень важно для нас',
    'review.comment_placeholder': 'Оставьте комментарий (необязательно)...',
    'review.submit': 'Отправить',
    // Arrival time
    'arrival.title': 'Выберите время',
    'arrival.subtitle': 'укажите когда подойдёте',
    'arrival.now': 'Сейчас',
    'arrival.now_desc': 'Готов ждать',
    'arrival.15min': '15 мин',
    'arrival.15min_desc': 'Через 15 минут',
    'arrival.30min': '30 мин',
    'arrival.30min_desc': 'Через 30 минут',
    'arrival.1hour': '1 час',
    'arrival.1hour_desc': 'Через 1 час',
    'arrival.custom': 'Другое',
    'arrival.custom_desc': 'Указать время',

    'review.skip': 'Пропустить',
  },

  en: {
    'app.name': 'GazQueue',
    'header.login': 'Sign In',
    'header.profile': 'Profile',
    'header.back': 'Back',
    'header.theme.light': 'Dark mode',
    'header.theme.dark': 'Light mode',

    'hero.badge': 'Tashkent · Real-time queue system',
    'hero.title1': 'Manage your',
    'hero.title2': 'gas queue online',
    'hero.desc': 'Find the nearest gas station, track queues in real-time, and save your time. 18 methane stations connected.',
    'hero.btn.queue': '🚗 Join Queue',
    'hero.btn.find': '📍 Find Station',
    'hero.trust.realtime': 'Real-time updates',
    'hero.trust.secure': 'Secure system',
    'hero.trust.mobile': 'Mobile friendly',

    'stats.total': 'Total stations',
    'stats.open': 'Open stations',
    'stats.online': 'Users online',
    'stats.active': 'Active queues',
    'stats.avgwait': 'Avg wait time',
    'stats.today': 'Served today',

    'map.title': 'Methane station map',
    'map.desc': '18 stations across Tashkent · Pick a station on the map',
    'map.filter': 'Status:',
    'map.free': 'No queue',
    'map.medium': 'Medium',
    'map.busy': 'Busy',
    'map.nearest': 'Nearest',
    'map.route': 'Route',
    'map.station_count': 'stations',
    'map.nearest_label': 'Nearest:',
    'map.route_label': 'Route:',

    'stations.title': 'Nearest stations',
    'stations.queue': 'cars',
    'stations.wait': 'min',
    'stations.join': 'Join queue →',
    'stations.open': 'Open',
    'stations.closed': '🔒 Closed',
    'stations.cars': 'cars',
    'stations.rating': '★',

    'queue.title': 'Online queue',
    'queue.selected': 'Selected station',
    'queue.select_prompt': '⬆️ Select a station on the map',
    'queue.gas_yes': '✅ Gas available',
    'queue.gas_no': '❌ Gas unavailable',
    'queue.status': 'Queue status',
    'queue.empty': 'Queue is empty',
    'queue.you': 'You',
    'queue.first': 'Now serving',
    'queue.name': 'Name',
    'queue.name_placeholder': 'Your full name',
    'queue.car': 'Car number',
    'queue.car_placeholder': 'Example: 01 A 123 BC',
    'queue.gas_amount': 'Gas amount',
    'queue.join_btn': '🚗 Join Queue',
    'queue.leave_btn': 'Leave Queue',
    'queue.loading': 'Loading...',
    'queue.position': 'position',
    'queue.ahead': 'people ahead',
    'queue.at_station': '- queued at station',

    'reg.title': 'Create your account',
    'reg.subtitle': 'Join the queue online via GazQueue',
    'reg.tab.register': 'Register',
    'reg.tab.login': 'Sign In',
    'reg.fullname': 'Full name',
    'reg.phone': 'Phone number',
    'reg.carnumber': 'Car number',
    'reg.car_example': 'Example: 01 A 123 BC or 30 BBA 456',
    'reg.password': 'Password',
    'reg.password_hint': 'At least 8 characters',
    'reg.confirm': 'Confirm password',
    'reg.confirm_hint': 'Enter password again',
    'reg.terms1': 'Terms of Service',
    'reg.terms2': 'Privacy Policy',
    'reg.terms_agree': 'I agree with',
    'reg.submit': 'Register',
    'reg.login_title': 'Sign in to your account',
    'reg.login_phone': 'Phone number',
    'reg.login_password': 'Password',
    'reg.login_forgot': 'Forgot password?',
    'reg.login_submit': 'Sign In',
    'reg.login_checking': 'Checking...',
    'reg.info_title': 'Why register?',
    'reg.info_desc': 'An account is needed to join queues online, track your status, and receive notifications.',
    'reg.success_title': 'Success! 🎉',
    'reg.success_desc': 'You have successfully registered. Now you can join any queue.',
    'reg.success_btn': 'Go to Home',
    'reg.login_error': 'Wrong phone or password',
    'reg.login_network_error': 'Connection error',
    'reg.error.name': 'Please enter your full name.',
    'reg.error.phone': 'Please enter a complete phone number.',
    'reg.error.car': 'Please enter your car number.',
    'reg.error.password': 'Password must be at least 8 characters.',
    'reg.error.confirm': 'Passwords do not match.',
    'reg.error.terms': 'You must agree to the terms of service.',
    'reg.password_strength.very_weak': 'Very weak',
    'reg.password_strength.weak': 'Weak',
    'reg.password_strength.medium': 'Medium',
    'reg.password_strength.strong': 'Strong 💪',

    'toast.station_selected': 'selected',
    'toast.select_station': 'Please select a station on the map first',
    'toast.enter_name': 'Please enter your name',
    'toast.enter_car': 'Please enter your car number',
    'toast.select_gas': 'Please select gas amount',
    'toast.join_success': 'Successfully joined the queue! 🎉',
    'toast.leave_success': 'Left the queue',
    'toast.error': 'An error occurred',

    'gas.half': 'Half tank (~20L)',
    'gas.half_sub': '25,000 UZS',
    'gas.full': 'Full tank (~40L)',
    'gas.full_sub': '50,000 UZS',
    'gas.custom': 'Custom amount',
    'gas.custom_sub': "I'll tell",
    'gas.urgent': 'Urgent',
    'gas.urgent_sub': 'Just a bit',

    'footer.queue': 'Queue',
    'footer.azs': 'Stations',
    'footer.notifications': 'Notifications',
    'footer.admin': 'Admin',
    'footer.station': 'Station',
    'footer.profile': 'Profile',
    'footer.login': 'Sign In',

    'mob.home': 'Home',
    'mob.azs': 'Stations',
    'mob.queue': 'Queue',
    'mob.notif': 'Notifications',
    'mob.profile': 'Profile',

    'admin.panel': 'Admin Panel',
    'admin.nav.main': 'Main',
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.stations': 'Stations',
    'admin.nav.queues': 'Queues',
    'admin.nav.users': 'Users',
    'admin.nav.analytics': 'Analytics',
    'admin.nav.settings': 'Settings',
    'admin.nav.account': 'Account',
    'admin.logout': 'Logout',
    'admin.login.title': 'Admin Login',
    'admin.login.subtitle': 'For admin or AZS staff',
    'admin.login.phone': 'Phone number',
    'admin.login.password': 'Password',
    'admin.login.checking': 'Checking...',
    'admin.login.submit': 'Sign In',
    'admin.login.back': '← Back to home',
    'admin.login.error': 'Wrong phone or password',
    'admin.login.empty_error': 'Enter phone and password',
    'admin.login.generic_error': 'An error occurred',

    'station.login.title': 'Station Admin Login',
    'station.login.subtitle': 'For station staff',

    'station.panel': 'Admin panel',
    'station.gas.title': '⛽ Gas status (visible to customers)',
    'station.gas.yes': '✅ Gas available',
    'station.gas.no': '❌ Gas unavailable',
    'station.gas.message_placeholder': 'Additional message (optional)...',
    'station.gas.eta_placeholder': 'Arrival time (if unavailable)...',
    'station.gas.save': 'Save',
    'station.gas.saved': '✓ Saved',
    'station.sections': 'Sections',
    'station.sections.count': 'Section count:',
    'station.sections.empty': 'Empty',
    'station.sections.done': '✓ Done',
    'station.queue': 'Queue list',
    'station.queue.clear': 'Clear',
    'station.queue.empty': 'Queue is empty',
    'station.stats.queue': 'In queue',
    'station.stats.served': 'Served',
    'station.stats.busy': 'Busy sections',
    'station.stats.today': 'Served today',
    'station.history': 'Refueling history',
    'station.history.browser': 'Stored in browser',
    'station.history.empty': 'No refuelings yet',
    'station.history.clear': 'Clear',
    'station.history.confirm_clear': 'Are you sure you want to clear all history?',
    'station.confirm_clear_queue': 'Are you sure you want to clear the queue?',
    'station.reviews': 'Customer reviews',
    'station.reviews.empty': 'No reviews yet',
    'station.reviews.avg': 'average',
    'station.reviews.ta': '',
    'station.logout': 'Logout',

    'history.title': 'Refueling history',
    'history.stats.today': 'Today',
    'history.stats.total': 'Total',
    'history.stats.top': 'Most requested',
    'history.filter': 'Filter:',
    'history.filter.all': 'All',
    'history.filter.today': 'Today',
    'history.filter.week': 'This week',
    'history.search': 'Name or car number...',
    'history.empty.title': 'History is empty',
    'history.empty.desc': 'Will appear here after refueling',
    'history.table.number': '#',
    'history.table.name': 'Name',
    'history.table.car': 'Car',
    'history.table.gas': 'Gas amount',
    'history.table.section': 'Section',
    'history.table.time': 'Date · Time',
    'history.today': 'Today',
    'history.clear': 'Clear',
    'history.confirm_clear': 'Are you sure you want to clear all history?',

    'notif.title': 'Notifications',
    'notif.read_all': 'Mark all as read',
    'notif.empty.title': 'No notifications',
    'notif.empty.desc': 'Will appear here when you join a queue',
    'notif.login.title': 'Join a queue first',
    'notif.login.btn': 'Go to Home',
    'notif.just_now': 'Just now',
    'notif.min_ago': 'min ago',
    'notif.hour_ago': 'hour ago',

    'profile.overview': 'Profile',
    'profile.queue': 'My Queue',
    'profile.history': 'History',
    'profile.favorites': 'Favorites',
    'profile.settings': 'Settings',
    'profile.edit': '✏️ Edit',
    'profile.logout': '🚪 Logout',
    'profile.tab.overview': 'Overview',
    'profile.stats.queue': 'Queue',
    'profile.stats.visits': 'Visits',
    'profile.stats.favorites': 'Favorites',
    'profile.stats.none': 'None',
    'profile.active_queue': '⛽ Active queue',
    'profile.view': 'View',
    'profile.recent_notifs': '🔔 Recent notifications',
    'profile.see_all': 'See all →',
    'profile.fav_stations': '⭐ Favorite stations',
    'profile.my_queue': '🚗 My queue',
    'profile.queue_active': 'You are in queue',
    'profile.queue_none': 'No active queue',
    'profile.queue_none_desc': "You are not currently queued at any station",
    'profile.queue_join': '🚗 Join Queue',
    'profile.queue_leave': 'Leave Queue',
    'profile.queue_position': 'Position',
    'profile.queue_total': 'In queue',
    'profile.queue_minutes': 'Minutes',
    'profile.queue_est': '~',
    'profile.history_title': '📋 Visit history',
    'profile.history_empty': 'History is empty',
    'profile.history_empty_desc': 'Will appear here after refueling',
    'profile.fav_title': '⭐ Favorite stations',
    'profile.fav_empty': 'No favorite stations',
    'profile.fav_empty_desc': 'Select a station on the map to add to favorites',
    'profile.fav_open_map': '📍 Open Map',
    'profile.settings_profile': '👤 Profile settings',
    'profile.settings_name': 'Name',
    'profile.settings_car': 'Car number',
    'profile.settings_phone_note': "📞 Contact admin to change phone number",
    'profile.settings_save': '💾 Update Profile',
    'profile.settings_password': '🔐 Change password',
    'profile.settings_old_pass': 'Old password',
    'profile.settings_new_pass': 'New password',
    'profile.settings_confirm_pass': 'Confirm new password',
    'profile.settings_pass_placeholder': 'At least 6 characters',
    'profile.settings_confirm_placeholder': 'Enter again',
    'profile.settings_pass_update': '🔒 Update password',
    'profile.settings_app_version': 'App version',
    'profile.settings_language': 'Language',
    'profile.settings_member_since': 'Member since',
    'profile.fav_station_open': '✅ Open',
    'profile.fav_station_closed': '🔒 Closed',
    'profile.open': 'Open',
    'profile.closed': 'Closed',

    'review.title': 'Rate our service',
    'review.desc': 'Service completed',
    'review.thanks_title': 'Thank you!',
    'review.thanks_desc': 'Your feedback is very important to us',
    'review.comment_placeholder': 'Leave a comment (optional)...',
    'review.submit': 'Submit',
    // Arrival time
    'arrival.title': 'Arrival time',
    'arrival.subtitle': 'when will you arrive',
    'arrival.now': 'Now',
    'arrival.now_desc': 'Ready to wait',
    'arrival.15min': '15 min',
    'arrival.15min_desc': 'In 15 minutes',
    'arrival.30min': '30 min',
    'arrival.30min_desc': 'In 30 minutes',
    'arrival.1hour': '1 hour',
    'arrival.1hour_desc': 'In 1 hour',
    'arrival.custom': 'Custom',
    'arrival.custom_desc': 'Pick a time',

    'review.skip': 'Skip',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('gazqueue_lang') || 'uz';
  });

  const changeLang = useCallback((l) => {
    setLang(l);
    localStorage.setItem('gazqueue_lang', l);
  }, []);

  const t = useCallback((key, params = {}) => {
    let text = TRANSLATIONS[lang]?.[key] || TRANSLATIONS['uz']?.[key] || key;
    // Replace params like {{name}}
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(new RegExp(`{{${k}}}`, 'g'), v);
    });
    return text;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  return ctx || { lang: 'uz', setLang: () => {}, t: (k) => k, languages: LANGUAGES };
}

export function useLanguage() {
  return useTranslation();
}
